# For workflow syntax reference, please see the documentation available on Github
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on:
  push:
  # schedule:
  #   - cron: "30 12 * * *" # Run the `main` branch daily at 12:30pm UTC / 5:30am PDT / 8:30am PDT
  workflow_dispatch: # Allow the workflow to be triggered manually
  repository_dispatch: # Allow the workflow to be triggered via HTTP
    types: [ci]

env:
  GCP_PRIVATE_KEY: ${{ secrets.GCP_PRIVATE_KEY }}
  GCP_PRIVATE_KEY_ID: ${{ secrets.GCP_PRIVATE_KEY_ID }}
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dbt-labs/dbt-bigquery:1.3.0
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: dbt debug
      run: dbt debug --profiles-dir $PWD
    - name: dbt deps
      run: dbt deps --profiles-dir $PWD
    - name: dbt build
      run: dbt build --profiles-dir $PWD